@echo off
echo 🧪 Running tests with coverage...
go test -cover ./internal/...
go test -coverprofile=coverage.out ./internal/...
go tool cover -html=coverage.out -o coverage.html
echo 📊 Coverage report: coverage.html